"use strict";
// Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
Object.defineProperty(exports, "__esModule", { value: true });
exports.TickerCanceled = exports.TickerFuture = exports.TweenSequenceItem = exports.FlippedTweenSequence = exports.TweenSequence = exports.CurveTween = exports.ConstantTween = exports.StepTween = exports.IntTween = exports.RectTween = exports.SizeTween = exports.ColorTween = exports.ReverseTween = exports.Tween = exports.Animatable = exports.AnimationLocalStatusListenersMixin = exports.AnimationLocalListenersMixin = exports.AnimationEagerListenerMixin = exports.AnimationLazyListenerMixin = exports.Curves = exports.ElasticInOutCurve = exports.ElasticOutCurve = exports.ElasticInCurve = exports.FlippedCurve = exports.CatmullRomCurve = exports.CatmullRomSpline = exports.Curve2DSample = exports.Curve2D = exports.Cubic = exports.Threshold = exports.Interval = exports.SawTooth = exports.Curve = exports.ParametricCurve = exports.AnimationMin = exports.AnimationMax = exports.AnimationMean = exports.CompoundAnimation = exports.TrainHoppingAnimation = exports.CurvedAnimation = exports.ReverseAnimation = exports.ProxyAnimation = exports.AnimationWithParentMixin = exports.AlwaysStoppedAnimation = exports.AnimationController = exports.AnimationBehavior = exports.Animation = exports.AnimationStatus = void 0;
const ticker_1 = require("./flutter/src/scheduler/ticker");
Object.defineProperty(exports, "TickerFuture", { enumerable: true, get: function () { return ticker_1.TickerFuture; } });
Object.defineProperty(exports, "TickerCanceled", { enumerable: true, get: function () { return ticker_1.TickerCanceled; } });
const tween_sequence_1 = require("./flutter/src/animation/tween-sequence");
Object.defineProperty(exports, "TweenSequence", { enumerable: true, get: function () { return tween_sequence_1.TweenSequence; } });
Object.defineProperty(exports, "FlippedTweenSequence", { enumerable: true, get: function () { return tween_sequence_1.FlippedTweenSequence; } });
Object.defineProperty(exports, "TweenSequenceItem", { enumerable: true, get: function () { return tween_sequence_1.TweenSequenceItem; } });
const tween_1 = require("./flutter/src/animation/tween");
Object.defineProperty(exports, "Animatable", { enumerable: true, get: function () { return tween_1.Animatable; } });
Object.defineProperty(exports, "Tween", { enumerable: true, get: function () { return tween_1.Tween; } });
Object.defineProperty(exports, "ReverseTween", { enumerable: true, get: function () { return tween_1.ReverseTween; } });
Object.defineProperty(exports, "ColorTween", { enumerable: true, get: function () { return tween_1.ColorTween; } });
Object.defineProperty(exports, "SizeTween", { enumerable: true, get: function () { return tween_1.SizeTween; } });
Object.defineProperty(exports, "RectTween", { enumerable: true, get: function () { return tween_1.RectTween; } });
Object.defineProperty(exports, "IntTween", { enumerable: true, get: function () { return tween_1.IntTween; } });
Object.defineProperty(exports, "StepTween", { enumerable: true, get: function () { return tween_1.StepTween; } });
Object.defineProperty(exports, "ConstantTween", { enumerable: true, get: function () { return tween_1.ConstantTween; } });
Object.defineProperty(exports, "CurveTween", { enumerable: true, get: function () { return tween_1.CurveTween; } });
const listener_helpers_1 = require("./flutter/src/animation/listener-helpers");
Object.defineProperty(exports, "AnimationLazyListenerMixin", { enumerable: true, get: function () { return listener_helpers_1.AnimationLazyListenerMixin; } });
Object.defineProperty(exports, "AnimationEagerListenerMixin", { enumerable: true, get: function () { return listener_helpers_1.AnimationEagerListenerMixin; } });
Object.defineProperty(exports, "AnimationLocalListenersMixin", { enumerable: true, get: function () { return listener_helpers_1.AnimationLocalListenersMixin; } });
Object.defineProperty(exports, "AnimationLocalStatusListenersMixin", { enumerable: true, get: function () { return listener_helpers_1.AnimationLocalStatusListenersMixin; } });
const curves_1 = require("./flutter/src/animation/curves");
Object.defineProperty(exports, "ParametricCurve", { enumerable: true, get: function () { return curves_1.ParametricCurve; } });
Object.defineProperty(exports, "Curve", { enumerable: true, get: function () { return curves_1.Curve; } });
Object.defineProperty(exports, "SawTooth", { enumerable: true, get: function () { return curves_1.SawTooth; } });
Object.defineProperty(exports, "Interval", { enumerable: true, get: function () { return curves_1.Interval; } });
Object.defineProperty(exports, "Threshold", { enumerable: true, get: function () { return curves_1.Threshold; } });
Object.defineProperty(exports, "Cubic", { enumerable: true, get: function () { return curves_1.Cubic; } });
Object.defineProperty(exports, "Curve2D", { enumerable: true, get: function () { return curves_1.Curve2D; } });
Object.defineProperty(exports, "Curve2DSample", { enumerable: true, get: function () { return curves_1.Curve2DSample; } });
Object.defineProperty(exports, "CatmullRomSpline", { enumerable: true, get: function () { return curves_1.CatmullRomSpline; } });
Object.defineProperty(exports, "CatmullRomCurve", { enumerable: true, get: function () { return curves_1.CatmullRomCurve; } });
Object.defineProperty(exports, "FlippedCurve", { enumerable: true, get: function () { return curves_1.FlippedCurve; } });
Object.defineProperty(exports, "ElasticInCurve", { enumerable: true, get: function () { return curves_1.ElasticInCurve; } });
Object.defineProperty(exports, "ElasticOutCurve", { enumerable: true, get: function () { return curves_1.ElasticOutCurve; } });
Object.defineProperty(exports, "ElasticInOutCurve", { enumerable: true, get: function () { return curves_1.ElasticInOutCurve; } });
Object.defineProperty(exports, "Curves", { enumerable: true, get: function () { return curves_1.Curves; } });
const animations_1 = require("./flutter/src/animation/animations");
Object.defineProperty(exports, "AlwaysStoppedAnimation", { enumerable: true, get: function () { return animations_1.AlwaysStoppedAnimation; } });
Object.defineProperty(exports, "AnimationWithParentMixin", { enumerable: true, get: function () { return animations_1.AnimationWithParentMixin; } });
Object.defineProperty(exports, "ProxyAnimation", { enumerable: true, get: function () { return animations_1.ProxyAnimation; } });
Object.defineProperty(exports, "ReverseAnimation", { enumerable: true, get: function () { return animations_1.ReverseAnimation; } });
Object.defineProperty(exports, "CurvedAnimation", { enumerable: true, get: function () { return animations_1.CurvedAnimation; } });
Object.defineProperty(exports, "TrainHoppingAnimation", { enumerable: true, get: function () { return animations_1.TrainHoppingAnimation; } });
Object.defineProperty(exports, "CompoundAnimation", { enumerable: true, get: function () { return animations_1.CompoundAnimation; } });
Object.defineProperty(exports, "AnimationMean", { enumerable: true, get: function () { return animations_1.AnimationMean; } });
Object.defineProperty(exports, "AnimationMax", { enumerable: true, get: function () { return animations_1.AnimationMax; } });
Object.defineProperty(exports, "AnimationMin", { enumerable: true, get: function () { return animations_1.AnimationMin; } });
const animation_controller_1 = require("./flutter/src/animation/animation-controller");
Object.defineProperty(exports, "AnimationBehavior", { enumerable: true, get: function () { return animation_controller_1.AnimationBehavior; } });
Object.defineProperty(exports, "AnimationController", { enumerable: true, get: function () { return animation_controller_1.AnimationController; } });
const animation_1 = require("./flutter/src/animation/animation");
Object.defineProperty(exports, "AnimationStatus", { enumerable: true, get: function () { return animation_1.AnimationStatus; } });
Object.defineProperty(exports, "Animation", { enumerable: true, get: function () { return animation_1.Animation; } });
